# Stage 0: Node 빌드
FROM node:18-alpine AS build

WORKDIR /app

# package.json만 먼저 복사
COPY ./frontend/front/package*.json ./
RUN npm install

# 나머지 코드 복사
COPY ./frontend/front/ ./
RUN npm run build

# Stage 1: Nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
